### ISSUE TITLE
Hi when will be fine tune code released?

### ISSUE THREAD

**Issue by FurkanGozukara** [Zeju1997/oft#1]
I am content producer of SECourses

Making a lot of content for stable diffusion training

When will your source code be released?

I would like to compare it with DreamBooth and make a tutorial video on my channel

https://www.youtube.com/SECourses

**Comment by Zeju1997** [comment]
Hi, thank you very much for your interest. The code will be released very soon. Best,

**Comment by wy1iu** [comment]
We have released an initial version. Thanks!

**Comment by i-amgeek** [comment]
@FurkanGozukara I would like to see the comparison results. Please share the video here if you create it.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara I would like to see the comparison results. Please share the video here if you create it.

I am interested in windows training

I see script files and readme is only for unix

a simple jupyter notebook or a google colab would be nice for the following
a gradio would be even more amazing 


```
accelerate launch train_dreambooth_oft.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir="$CLASS_DIR" \
  --output_dir="$OUTPUT_DIR" \
  --instance_prompt="$instance_prompt" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --class_prompt="$class_prompt" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=5000 \
  --learning_rate=5e-5 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=3005 \
  --validation_prompt="$validation_prompt" \
  --validation_epochs=1 \
  --seed="0" \
  --name="$name" \
  --num_class_images=200 \
  --eps=$eps \
  --rank=$rank \
  --coft
```

**Comment by Zeju1997** [comment]
Thank you so much for your suggestions, it's definitely a good suggestion.
Yes, we will keeping working on this repo and add more examples in the near future.
