### ISSUE TITLE
Have you tried training OFT on the SDXL

### ISSUE THREAD

**Issue by carvychen** [Zeju1997/oft#15]
If so, could you please also release the relevant training code?

**Comment by Zeju1997** [comment]
Hi,
thanks for the question. We did not test it on SDXL yet, but might add additional experiments of SDXL in the future.
Best,

**Comment by Zeju1997** [comment]
OFT has been integrated into the PEFT repository (https://github.com/huggingface/peft).
Here is the guide of finetuning dreamooth with PEFT-LoRA:
https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md
By changing the LoRAConfig to OFTConfig, finetuning SDXL can be easily achieved.
