### ISSUE TITLE
Quantitative comparative code

### ISSUE THREAD

**Issue by csguoh** [Zeju1997/oft#16]
Hi authors,
I can not find the quantitative evaluation code in this repo, such as the reproduce of Table1 in the main paper.  I would like to know how to do quantitative comparison or which repo should I refer to?
Thanks:D

**Comment by Zeju1997** [comment]
Hi,

thank you so much for the question. I followed the implementation of dreambooth (https://arxiv.org/pdf/2208.12242.pdf, table 1) to run the experiment in table 1.

Best,
