### ISSUE TITLE
Where is metadata.json that clip_text needs?

### ISSUE THREAD

**Issue by DaShenZi721** [Zeju1997/oft#18]

**Comment by Zeju1997** [comment]
Not entirely sure what you mean with the metadata.json. We generally followed Dreambooth table 1 for the experiments.
https://arxiv.org/pdf/2208.12242.pdf

**Comment by DaShenZi721** [comment]
The metadata.json is here, line 363 in oft-db/eval_ablation.py
 ` dataset = PromptDatasetCLIP(image_dir, 'metadata.json', tokenizer, processor, epoch)`

**Comment by Zeju1997** [comment]
Hi, so this is basically the .json file for each dataset with the captions listed. Because for calculating CLIP you would need the caption.

**Comment by Grapemaid** [comment]
Hi,I also encountered this problem, how should I solve it?
`Traceback (most recent call last):
  File "/root/oft/oft-db/eval.py", line 489, in <module>
    sim, criterion = clip_text(image_dir, epoch) # db: 0.1687191128730774 # lora: 0.1668722778558731 # cot: 0.16917628049850464
  File "/root/oft/oft-db/eval.py", line 359, in clip_text
    dataset = PromptDatasetCLIP(image_dir, 'metadata.json', tokenizer, processor, epoch)
  File "/root/oft/oft-db/eval.py", line 60, in __init__
    with open(json_file, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'metadata.json'`
