### ISSUE TITLE
How to get COCO dataset?

### ISSUE THREAD

**Issue by DaShenZi721** [Zeju1997/oft#19]
How to download and place COCO dataset such that I can get the directory structure as following?

└── COCO
│ ├── train
│ │ ├── color
│ │ ├── depth
│ ...

**Comment by Zeju1997** [comment]
For COCO dataset, we do not host the data for download, but you can easily download it from the official website (train/val 2017, train split for training and val for evaluation)
https://cocodataset.org/#download
We used BLIP to generate the captions to be consistent across different datasets.
Here are the captions for reference:
[coco_prompt_train_blip.json](https://github.com/Zeju1997/oft/files/14741923/coco_prompt_train_blip.json)
[coco_prompt_val_blip.json](https://github.com/Zeju1997/oft/files/14741925/coco_prompt_val_blip.json)

**Comment by DaShenZi721** [comment]
Hello, I have downloaded train/val 2017 from [this site](https://cocodataset.org/#download).
But the order of the extracted files does not seem to correspond to the order of the caption in these two files [coco_prompt_train_blip.json](https://github.com/Zeju1997/oft/files/14741923/coco_prompt_train_blip.json)
[coco_prompt_val_blip.json](https://github.com/Zeju1997/oft/files/14741925/coco_prompt_val_blip.json)

For example,
![image](https://github.com/Zeju1997/oft/assets/39253334/bc137c6f-d141-4384-9e59-d9fc786a91f9)
![image](https://github.com/Zeju1997/oft/assets/39253334/85943064-b1af-4bf5-8bd8-d3c9c9f42c7a)

**Comment by DaShenZi721** [comment]
Hello, I used this [Canny edge detector](https://github.com/adl1995/edge-detectors/tree/master), but the generated canny is not good. 
Could you please provide the code of the Canny edge detector you used?
Thanks a lot!

**Comment by csguoh** [comment]
Hi, sorry to bother you.

I have downloaded the COCO 2017val "[2017 Val images [5K/1GB]](http://images.cocodataset.org/zips/val2017.zip)" in the official website. However, I find the file name is not consist with the prompt json file you provided. 

The image list of the unziped COCO 2017 val is as follows:
<img width="328" alt="image" src="https://github.com/Zeju1997/oft/assets/68777880/cb056c75-2a9c-4f4e-b5b9-ebbed95f29ee">

The prompt json with BLIP is as follows:
<img width="805" alt="image" src="https://github.com/Zeju1997/oft/assets/68777880/3e9c76b9-4b31-4d79-8191-5513ea136ad9">

It seems the prompts do not match the images. Did I misunderstand something?

**Comment by DaShenZi721** [comment]
> Hi, sorry to bother you.
> 
> I have downloaded the COCO 2017val "[2017 Val images [5K/1GB]](http://images.cocodataset.org/zips/val2017.zip)" in the official website. However, I find the file name is not consist with the prompt json file you provided.
> 
> The image list of the unziped COCO 2017 val is as follows: <img alt="image" width="328" src="https://private-user-images.githubusercontent.com/68777880/339948989-cb056c75-2a9c-4f4e-b5b9-ebbed95f29ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mzk1NzcsIm5iZiI6MTcxODQzOTI3NywicGF0aCI6Ii82ODc3Nzg4MC8zMzk5NDg5ODktY2IwNTZjNzUtMmE5Yy00ZjRlLWI1YjktZWJiZWQ5NWYyOWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA4MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OTc4NWFhYzdiNmJhODg3ZjUyNTU0OWU4MzdkYzY2NDAwMzdkODQ4ZTA0OTNmMTc4ZTU2M2IyMGMzYzQyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMDtBUme6KXJLvpwMGapjLR1EuMumeRFyE5vQX1hQLs">
> 
> The prompt json with BLIP is as follows: <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/68777880/339949009-3e9c76b9-4b31-4d79-8191-5513ea136ad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mzk1NzcsIm5iZiI6MTcxODQzOTI3NywicGF0aCI6Ii82ODc3Nzg4MC8zMzk5NDkwMDktM2U5Yzc2YjktNGIzMS00ZDc5LTgxOTEtNTUxM2VhMTM2YWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA4MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTVmODJiMDc0YTRhNzA0YzBhYTljNGU1YTE5ZjA2NWY3YjdhY2Y4N2RkNmQ3ZDRlMTM5ZWExMTExZDBkYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CrEgzLKs-JFJ5XXwgKuqjaMkiwjejJijdZP7EP1Gg4Q">
> 
> It seems the prompts do not match the images. Did I misunderstand something?

Because the prompt jsons with BLIP are in an inconsistent order with origin COCO dataset, you'd better regenerate the prompts by following the process procedure of COCO in the appendix.

**Comment by csguoh** [comment]
Get it! Thanks for your reply.
