### ISSUE TITLE
Can subject-driven or controllable generation pipelines be integrated with inpainting models? 

### ISSUE THREAD

**Issue by i-amgeek** [Zeju1997/oft#3]

**Comment by Zeju1997** [comment]
Hi, thank you for your interest in our project. I am not so familiar with the inpainting task, but to summarize our project, what we propose is a new fine-tuning method, that can be applied to all the tasks where LoRA can be applied. So if you have seen LoRA on the tasks you are working on, our method can also be used there. 

I will add some examples in Readme of how to use our fine-tuning method on its own.

**Comment by StephanPan** [comment]
can i both use subject images and control signal such as detph as the input to finetune the model, so that the style and the stucture embedding can be both trained.
